repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        files: \.(cpp|hpp|cc|c|h)$
        args:
          - --style=file   # use your .clang-format in repo root

  - repo: local
    hooks:
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy
        language: system
        types: [c++]
        files: \.(cpp|cc|cxx|h|hpp)$
        args:
          - -p=build       # points to build folder with compile_commands.json
          - --quiet        # optional: suppress extra output
          - --config-file=.clang-tidy  # ensure it uses your repo config

      - id: cppcheck
        name: cppcheck
        entry: cppcheck --enable=all --inconclusive --quiet
        language: system
        types: [c++]
        files: \.(cpp|cc|cxx|h|hpp)$
